import { ROLE } from "./constants";

export const menusData = [
  {
    menu_id: 100,
    menu_name: "My Dashboard",
    icon: "LayoutDashboard",
    sorting: 1,
    url: "/",
    permission: ["admin", "super_admin", "customer", "staff"],
    parent_id: null,
    children: [],
  },
  {
    menu_id: 200,
    menu_name: "User Management",
    icon: "Users",
    sorting: 2,
    url: "/user-management",
    permission: ["admin", "super_admin"],
    parent_id: null,
    children: [
      {
        menu_id: 201,
        menu_name: "Admin",
        url: "/user-management/admin",
        permission: ["super_admin"],
        parent_id: 200,
      },
      {
        menu_id: 202,
        menu_name: "Staff",
        url: "/user-management/staff",
        permission: ["admin", "super_admin"],
        parent_id: 200,
      },
      {
        menu_id: 203,
        menu_name: "Customer",
        url: "/user-management/customer",
        permission: ["admin", "super_admin"],
        parent_id: 200,
      },
    ],
  },
  {
    menu_id: 300,
    menu_name: "Warehouse Settings",
    icon: "Warehouse",
    sorting: 3,
    url: "/admin/warehouse",
    permission: [ROLE.ADMIN, ROLE.SUPER_ADMIN],
    parent_id: null,
    children: [
      {
        menu_id: 301,
        menu_name: "Location Mapping",
        url: "/warehouse/locations",
        permission: [ROLE.ADMIN, ROLE.SUPER_ADMIN],
        parent_id: 300,
      },
    ],
  },
  {
    menu_id: 400,
    menu_name: "Inventory",
    icon: "Boxes",
    sorting: 4,
    url: "/inventory",
    permission: ["super_admin"],
    parent_id: null,
    children: [],
  },
  {
    menu_id: 500,
    menu_name: "Orders",
    icon: "ShoppingCart",
    sorting: 5,
    url: "/orders",
    permission: [ROLE.ADMIN, ROLE.CUSTOMER, ROLE.SUPER_ADMIN],
    parent_id: null,
    children: [],
  },
  {
    menu_id: 600,
    menu_name: "Subscription",
    icon: "ShoppingCart",
    sorting: 6,
    url: "/subscription",
    permission: [ROLE.CUSTOMER],
    parent_id: null,
    children: [],
  },
];