import { ROLE } from "./constants";

export const menusData = [
  {
    menu_id: 100,
    menu_name: "My Dashboard",
    icon: "LayoutDashboard",
    sorting: 1,
    url: "/",
    permission: ["admin", "super_admin", "customer", "staff"],
    parent_id: null,
    children: [],
  },
  {
    menu_id: 200,
    menu_name: "User Management",
    icon: "Users",
    sorting: 2,
    url: "/user-management",
    permission: ["admin", "super_admin"],
    parent_id: null,
    children: [
      {
        menu_id: 201,
        menu_name: "Admin",
        url: "/user-management/admin",
        permission: ["super_admin"],
        parent_id: 200,
      },
      {
        menu_id: 202,
        menu_name: "Staff",
        url: "/user-management/staff",
        permission: ["admin", "super_admin"],
        parent_id: 200,
      },
      {
        menu_id: 203,
        menu_name: "Customer",
        url: "/user-management/customer",
        permission: ["admin", "super_admin"],
        parent_id: 200,
      },
    ],
  },
  {
    menu_id: 300,
    menu_name: "Warehouse Settings",
    icon: "Warehouse",
    sorting: 3,
    url: "/admin/warehouse",
    permission: ["admin", "super_admin"],
    parent_id: null,
    children: [
      {
        menu_id: 301,
        menu_name: "Location Mapping",
        url: "/admin/warehouse/locations",
        permission: ["admin", "super_admin"],
        parent_id: 300,
      },
    ],
  },
  {
    menu_id: 400,
    menu_name: "Operations Desk",
    icon: "Home",
    sorting: 1,
    url: "/staff/dashboard",
    permission: [ROLE.ADMIN, ROLE.SUPER_ADMIN, ROLE.CUSTOMER, ROLE.STAFF],
    parent_id: null,
    children: [],
  },
  {
    menu_id: 500,
    menu_name: "Order Management",
    icon: "ShoppingCart",
    sorting: 1,
    url: "/customer/orders",
    permission: [ROLE.CUSTOMER],
    parent_id: null,
    children: [
      {
        menu_id: 501,
        menu_name: "Create New Order",
        url: "/customer/orders/new",
        permission: [ROLE.CUSTOMER],
        parent_id: 500,
      },
      {
        menu_id: 502,
        menu_name: "Order History",
        url: "/customer/orders/history",
        permission: [ROLE.CUSTOMER],
        parent_id: 500,
      },
    ],
  },
];
