export const menusData = [
  {
    menu_id: 100,
    menu_name: "My Dashboard",
    icon: "LayoutDashboard",
    sorting: 1,
    url: "/",
    type: "admin",
    parent_id: null,
    children: [],
  },
  {
    menu_id: 200,
    menu_name: "User Management",
    icon: "Users",
    sorting: 2,
    url: "/users",
    type: "admin",
    parent_id: null,
    children: [
      {
        menu_id: 201,
        menu_name: "Staff",
        url: "/users/staff",
        type: "admin",
        parent_id: 200,
      },
      {
        menu_id: 202,
        menu_name: "Customer",
        url: "/users/customer",
        type: "admin",
        parent_id: 200,
      },
    ],
  },
  {
    menu_id: 300,
    menu_name: "Warehouse Settings",
    icon: "Warehouse",
    sorting: 3,
    url: "/admin/warehouse",
    type: "admin",
    parent_id: null,
    children: [
      {
        menu_id: 301,
        menu_name: "Location Mapping",
        url: "/admin/warehouse/locations",
        type: "admin",
        parent_id: 300,
      },
    ],
  },
  {
    menu_id: 400,
    menu_name: "Operations Desk",
    icon: "Home",
    sorting: 1,
    url: "/staff/dashboard",
    type: "staff",
    parent_id: null,
    children: [],
  },

  {
    menu_id: 500,
    menu_name: "Order Management",
    icon: "ShoppingCart",
    sorting: 1,
    url: "/customer/orders",
    type: "customer",
    parent_id: null,
    children: [
      {
        menu_id: 501,
        menu_name: "Create New Order",
        url: "/customer/orders/new",
        type: "customer",
        parent_id: 500,
      },
      {
        menu_id: 502,
        menu_name: "Order History",
        url: "/customer/orders/history",
        type: "customer",
        parent_id: 500,
      },
    ],
  },
  {
    menu_id: 600,
    menu_name: "Settings",
    icon: "Settings",
    sorting: 2,
    url: "/customer/profile",
    type: "customer",
    parent_id: null,
    children: [],
  },
];
